[package]
name = "restaking"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
deployer = "0x0a56762ce4e11553d450c1db24fdfd204176d31179e72027319bbce9dc3a1376"
restaking = "0xa1caf02e1756e085e53193897b8dfa80cb2b2a0858537b1a92a9eb477ba0bcad"

[dev-addresses]
# deployer = "0xcafe"
# restaking = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
