[package]
name = "restaking"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
deployer = "0x709d94d97776c7fe9a78fb24f181067d17a42bef3a911f3632321b41f69d8b63"
restaking = "0x73b0111387aec1031a2e9c0d616e39e268b2c0c4a488b7b6b9ab2399dc86a14d"

[dev-addresses]
# deployer = "0xcafe"
restaking = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
